### ISSUE TITLE
Fix Download Route

### ISSUE THREAD

**Issue by MilanDonhowe** [OSU-Sustainability-Office/osu_carbon_calculator_update_project#35]
[This function](https://github.com/OSU-Sustainability-Office/osu_carbon_calculator_update_project/blob/3f8580054c20f528b58aa2f4eda60862afcdcd67/backend/app/carbon/app.js#L40) is generating a internal server error regardless of the context in which it gets invoked which is bricking the carbon calculator and preventing it from working.  We need to debug why this route breaks on each invocation.

**Comment by solderq35** [comment]
Should be completed by https://github.com/OSU-Sustainability-Office/osu_carbon_calculator_update_project/pull/37
